### ISSUE TITLE
BL3M - Infinite Slide - Only functions for player 1 2-4 don't get the affect.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [apocalyptech/bl3hotfixmodding#5]
So I really enjoy infinite slide for shenanigans. However in MP only I can use it as I am player one. Can you fix it when you get a chance please? https://github.com/BLCM/bl3mods/wiki/Infinite%20Slide

**Comment by P3rf3ctXZer0** [comment]
If you need me find me here. Zer0TheAvowedRD#2995 https://discord.gg/ezJDf7vY

**Comment by apocalyptech** [comment]
Howdy!  I'm afraid I've got no clue about how any of this interacts with multiplayer.  The general recommendation with this kind of modding (for BL2/TPS/BL3) is that everyone joined to the same game should be running the exact same modset, to prevent any weird problems (like only one person being able to use infinite slide).  Obviously if you're playing with folks on consoles, that's not really possible, of course, but c'est la vie.

It's possible that there *is* some way to get that to work even if only the host is running it, but I don't really have any interest in trying to track down multiplayer bugs.  If you (or anyone else) manages to figure out a fix for it which makes it work fully in multiplayer, though, I'd be happy to merge in that fix.  :)

Anyway, cheers!  Good luck!

**Comment by P3rf3ctXZer0** [comment]
Understood thanks for the mod though it is definitely fun. Sad it only seems to work with sp though :(
